version: 2
jobs:
  test:
    working_directory: ~/blob-store
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run: echo '//registry.npmjs.org/:_authToken='$NPM_PRIVATE_AUTH_TOKEN > $HOME/.npmrc
      - restore_cache:
          keys:
            - v1-node_modules-{{ checksum "package.json" }}
            - v1-node_modules-
      - run: npm install
      - save_cache:
          key: v1-node-modules-{{ checksum "package.json" }}
          paths:
            - v1-node_modules-{{ checksum "package.json" }}
      - run: npm test
      - persist_to_workspace:
          root: ~/blob-store
          paths: .

  publish:
    working_directory: ~/blob-store
    docker:
      - image: circleci/node:dubnium
    steps:
      - attach_workspace:
          at: ~/blob-store
      - run:
          name: Authenticate with registry
          command: echo '//registry.npmjs.org/:_authToken='$NPM_PRIVATE_AUTH_TOKEN > $HOME/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:  # required since `publish` has tag filters AND requires `test`
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
